package com.example.bgloh.firebasetrial4;

import android.provider.Settings;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.JsonReader;
import android.util.Log;
import android.view.View;
import android.widget.Adapter;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import org.json.JSONObject;
import org.json.JSONStringer;

import java.util.ArrayList;
import java.util.Arrays;

public class MainActivity extends AppCompatActivity {


    DatabaseReference mPostReference;
    Person person1 = new Person();


    //listView
    private ListView mainListView ;
    private ArrayAdapter<String> listAdapter ;


    @Override
    protected void onCreate(Bundle savedInstanceState) {

        // super class constructor
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        // Button view
        Button mSave = (Button)findViewById(R.id.SaveButton);

        // Initialize Database
        mPostReference = FirebaseDatabase.getInstance().getReference()
                .child("persons");

        //Button Callback
       mSave.setOnClickListener(new View.OnClickListener() {
           @Override
           public void onClick(View v) {
               // Initialization

               EditText mName = (EditText) findViewById(R.id.NameEditText);
               EditText mAddress = (EditText) findViewById(R.id.AddressEditText);
               person1.setName(mName.getText().toString());
               person1.setAddress(mAddress.getText().toString());

               // Firebase db instantiation
               FirebaseDatabase database = FirebaseDatabase.getInstance();

               // Firebase db reference
               DatabaseReference myRef = database.getReference().child("persons");

              // Generate db data key
               String userId = myRef.push().getKey();

               // write person1 to persons db with an autogenerated key
               myRef.child(userId).setValue(person1);

             //  Log.d("firebaseD", person1.getName());

           }
       }
    );
}

    @Override
    public void onStart() {
        super.onStart();

        // Find the ListView resource.
        mainListView = (ListView) findViewById( R.id.listview );

        // Data list
        final ArrayList<String> personLists = new ArrayList<String>();

        // Create ArrayAdapter using the data list.
        listAdapter = new ArrayAdapter<String>(this, R.layout.simplerow, personLists);

        // Read from the database

        // number of data to fetch
        final int noOfDataToFetch = 4;

        // add event listener for fetching data from firebase database
        mPostReference.limitToLast(noOfDataToFetch).orderByChild("name").equalTo("kim").addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                // This method is called once with the initial value and again
                // whenever data at this location is updated.
                // String value = dataSnapshot.getValue(String.clas
                // s);

                // textView for information display
                TextView mPersonInfo = (TextView) findViewById(R.id.PersonTextView);

                // clear personLists before data display
                personLists.clear();

                for (DataSnapshot snapshot : dataSnapshot.getChildren()){

                    // retrieve person data from firebase database
                    Person user =   snapshot.getValue(Person.class);

                    // create String result
                    String result = "name: " + user.name + ", address: " + user.address;

                    // add person data to personLists
                    personLists.add(result);
                };


                // Set the ArrayAdapter as the ListView's adapter.
                mainListView.setAdapter( listAdapter );

                // Display person data information
                mPersonInfo.setText("last " + Integer.toString(noOfDataToFetch) + " persons lists ===>");


            }

            @Override
            public void onCancelled(DatabaseError error) {
                // Failed to read value
                Log.w("firebaseD", "Failed to read value.", error.toException());
            }
        });
        //
    }


    // Custom Class



    //

    @Override
    public void onDestory(){
        super.onDestroy();
        //
    }

}
